name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # ✅ Step 1: Checkout your repo so that snk can generate files into it
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Generate the SVG file
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shashankdotio
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      # ✅ Step 3: Publish to GitHub Pages (output branch)
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
