name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate both snake versions
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shashankdotio
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      # Push them to the 'output' branch
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
